service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: default
  region: eu-west-1
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::rss-task-5"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::rss-task-5/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: "get"
          path: "import"
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: rss-task-5
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
